### ISSUE TITLE
Cannot query subgraph deployed to `aurora` network on The Graph 

### ISSUE THREAD

**Issue by linguists** [aurora-is-near/aurora-relayer#145]
Following the The Graph tutorial for Aurora https://doc.aurora.dev/develop/indexers/thegraph, we can successfully deploy the subgraph to `aurora-testnet` network on The Graph, and the query works well: https://thegraph.com/hosted-service/subgraph/linguists/aurora-graph-testnet (You can try the example query in the Playground. )

![image](https://user-images.githubusercontent.com/95207870/146424726-8f2764a0-91db-47be-9fd9-66568312ebb9.png)

However, after deploy the same subgraph to `aurora` network on The Graph, the query doesn't work: https://thegraph.com/hosted-service/subgraph/linguists/aurora-graph

(No results were returned, but actually two transactions are executed: https://explorer.mainnet.aurora.dev/address/0x0Dc149c1adC89768381564c33Fff92820F328Ca7/transactions)

![image](https://user-images.githubusercontent.com/95207870/146424779-58517422-9ad0-4423-9079-260dcde9c53f.png)

Below are the `subgraph.yaml` for aurora testnet and mainnet in the tutorial project: https://github.com/aurora-is-near/example-subgraph. You can also find the contract addresses for testnet and mainnet below. 

- `aurora-testnet.subgraph.yml`

```yml
specVersion: 0.0.2
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Gravity
    network: aurora-testnet
    source:
      address: '0x60971C652A540F00BCbE0eb5792B2c00E1221BdB'
      abi: Gravity
      startBlock: 75237286
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - Gravatar
      abis:
        - name: Gravity
          file: ./abis/Gravity.json
      eventHandlers:
        - event: NewGravatar(uint256,address,string,string)
          handler: handleNewGravatar
        - event: UpdatedGravatar(uint256,address,string,string)
          handler: handleUpdatedGravatar
      file: ./src/mapping.ts
```

- `aurora-mainnet.subgraph.yml`

```yml
specVersion: 0.0.2
description: Gravatar for Ethereum
repository: https://github.com/graphprotocol/example-subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Gravity
    network: aurora
    source:
      address: '0x0Dc149c1adC89768381564c33Fff92820F328Ca7'
      abi: Gravity
      startBlock: 55295109
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - Gravatar
      abis:
        - name: Gravity
          file: ./abis/Gravity.json
      eventHandlers:
        - event: NewGravatar(uint256,address,string,string)
          handler: handleNewGravatar
        - event: UpdatedGravatar(uint256,address,string,string)
          handler: handleUpdatedGravatar
      file: ./src/mapping.ts

```
